### ISSUE TITLE
atf-v1.3-armada-17.10 doesn't compile with gcc 7.2

### ISSUE THREAD

**Issue by berolinux** [MarvellEmbeddedProcessors/atf-marvell#1]
atf-v1.3-armada-17.10 fails to build with gcc 7.2:

$ make USE_COHERENT_MEM=0 LOG_LEVEL=20 MV_DDR_PATH=$(pwd)/../mv-ddr-marvell PLAT=a80x0_mcbin CROSS_COMPILE=aarch64-linux-gnu- LD=aarch64-linux-gnu-ld.bfd all fip
[...]
lib/psci/psci_common.c: In function ‘psci_do_state_coordination’:
lib/psci/psci_common.c:220:27: error: array subscript is above array bounds [-Werror=array-bounds]
  psci_req_local_pwr_states[pwrlvl - 1][cpu_idx] = req_pwr_state;
  ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
cc1: all warnings being treated as errors

**Comment by berolinux** [comment]
ping... pull request for fix submitted >2 months ago

**Comment by haklai** [comment]
Merged in: https://github.com/MarvellEmbeddedProcessors/atf-marvell/commits/atf-v1.3-armada-17.10
